import Layout from '@layouts/Layout';
import Head from 'next/head';
import ReactLoading from 'react-loading';
import { toast, ToastContainer } from 'react-toastify';
import { data } from 'utils/data';
import _ from 'lodash';
import DateFilters from '@components/DateFilters';
import ActionButtons from '@components/ActionButtons';
import { RecogidasContextProvider } from '@context/recogidasContext';
import { ModalRecogidas } from '@components/modals/ModalRecogidas';
import Modal from '@components/modals/Modal';
import { ModalDespachos } from '@components/modals/ModalDespachos';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <RecogidasContextProvider>
          <RecogidasDespachos />
        </RecogidasContextProvider>
      </Layout>
    </>
  );
}

const RecogidasDespachos = () => {
  return (
    <div className='flex h-full w-full flex-col gap-2 p-4'>
      <div className='flex justify-center'>
        <h1>Recogidas y despachos</h1>
      </div>
      <div className='flex justify-between'>
        <DateFilters />
        <ActionButtons />
      </div>
      <DesktopTable />
      <MobileCards />

      <ModalRecogidas />
      <ModalDespachos />
    </div>
  );
};

const DesktopTable = () => {
  const datos = _.groupBy(data, 'Fecha');
  console.log(datos);

  return (
    <div className='hidden h-full flex-col md:flex'>
      <div className='debug flex h-full justify-center p-6'>
        <table className='block'>
          <thead>
            <tr>
              <th>Fecha</th>
              <th>Lote 1</th>
              <th>Lote 2</th>
              <th>Lote 3</th>
              <th>Lote 4</th>
              <th>Lote 5</th>
              <th>Lote 6</th>
              <th>Lote 7</th>
              <th>Lote 8</th>
              <th>Lote 9</th>
              <th>Lote 10</th>
            </tr>
          </thead>
          <tbody>
            {Object.keys(datos).map((fecha) => {
              return (
                <tr key={`row_${fecha}`}>
                  <td>
                    <div>{fecha}</div>
                  </td>
                  {datos[fecha].map((lote) => {
                    return (
                      <td key={`row_${fecha}_${lote.Lote}`}>
                        <div>{lote.Racimos}</div>
                      </td>
                    );
                  })}
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
      <div>Paginacion</div>
    </div>
  );
};

const MobileCards = () => {
  return (
    <div className='grid h-full grid-cols-2 md:hidden'>
      <div>
        <span>Lote 1</span>
        <div className='flex'>
          <div>Dato 1</div>
          <div>Dato 2</div>
        </div>
      </div>
      <div>
        <span>Lote 2</span>
        <div className='flex'>
          <div>Dato 1</div>
          <div>Dato 2</div>
        </div>
      </div>
      <div>
        <span>Lote 3</span>
        <div className='flex'>
          <div>Dato 1</div>
          <div>Dato 2</div>
        </div>
      </div>
      <div>
        <span>Lote 4</span>
        <div className='flex'>
          <div>Dato 1</div>
          <div>Dato 2</div>
        </div>
      </div>
    </div>
  );
};
