import Layout from '@layouts/Layout';
import Head from 'next/head';
import ReactLoading from 'react-loading';
import { toast, ToastContainer } from 'react-toastify';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <div className='flex h-full w-full flex-col'>
          <div className='flex justify-center'>
            <h1>Titulo</h1>
          </div>
          <div className='flex justify-between'>
            <div>Filtros</div>
            <div className='flex gap-2'>
              <button>Nueva recogida</button>
              <button>Nuevo despacho</button>
            </div>
          </div>
          <DesktopTable />
          <MobileCards />
        </div>
      </Layout>
    </>
  );
}

const DesktopTable = () => {
  const fireAlert = () => {
    toast.success('Esto es una alerta de success');
    toast.warning('Esto es una alerta de warning');
    toast.error('Esto es una alerta de error');
  };
  return (
    <div className='hidden h-full flex-col md:flex'>
      <div className='debug h-full'>
        tabla
        <button onClick={fireAlert}>Disparar alerta</button>
        <ReactLoading type='bars' color='blue' height={50} width={50} />
      </div>
      <div>Paginacion</div>
    </div>
  );
};

const MobileCards = () => {
  return (
    <div className='grid h-full grid-cols-2 md:hidden'>
      <div>
        <span>Lote 1</span>
        <div className='flex'>
          <div>Dato 1</div>
          <div>Dato 2</div>
        </div>
      </div>
      <div>
        <span>Lote 2</span>
        <div className='flex'>
          <div>Dato 1</div>
          <div>Dato 2</div>
        </div>
      </div>
      <div>
        <span>Lote 3</span>
        <div className='flex'>
          <div>Dato 1</div>
          <div>Dato 2</div>
        </div>
      </div>
      <div>
        <span>Lote 4</span>
        <div className='flex'>
          <div>Dato 1</div>
          <div>Dato 2</div>
        </div>
      </div>
    </div>
  );
};
